apiVersion: v1
kind: ConfigMap
metadata:
  name: github-wrapped-config
  namespace: github-wrapped
  labels:
    app: github-wrapped
data:
  BACKEND_URL: "http://github-wrapped-backend:5000"
  FRONTEND_PORT: "5173"
  NODE_ENV: "production"
